version: '3.3'
services:
  orai:
    container_name: orai_node
    image: orai/orai:0.40.3-alpine-dev
    working_dir: /workspace
    tty: true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 1307:1317
      - 26646:26656
      - 26647:26657
      - 9080:9090
    cap_add:
      - SYS_PTRACE
    env_file:
      - orai.env
    volumes:
      - ./:/workspace
      - oraivisor:/root/oraivisor
 

volumes:
  oraivisor: null
